### ISSUE TITLE
0xABBB - Set I to NNN only accepts code labels as arguments 

### ISSUE THREAD

**Issue by u1tralord** [jonesdy/Chip8-Assembler#5]
For the assembly code:

    ind 51

The assembler returns an error and refuses to compile. 
The error states:

    Label 51 does not exist.

Assembler Problem Code: 

    else if(!tokens[ti].compare("ind"))
    {
        // Sets I to address NNN, ANNN
        std::string arg = tokens[++ti];
        // Should be a code label *** Should not need code label to set memory pointer ***
        int loc = getLabelLocation(arg);
        if(loc == -1)
        {
            error = true;
            std::cout<<"Label "<<arg<<" does not exist."<<std::endl;
        }
        else
        {
            opcode = 0xA000 | (loc & 0x0FFF);
        }
        ti++;
    }

**Comment by jonesdy** [comment]
Thanks for submitting this issue. I'm surprised anybody is looking at this at all (I also haven't updated it in almost 2 years).
This problem would also be in jmp and jmp0, possibly others (we could add constants to call as well).

I'll take a look at it this weekend and see if I can get it fixed.

**Comment by jonesdy** [comment]
This was fixed in commit 9006de0.

**Comment by u1tralord** [comment]
Yeah, I guess I am little late to the party with that bug report. I just started getting into emulation and found your repo on the front page of a google search. Your emulator and assembler helped me a ton in writing and programming my own chip8 emulator https://github.com/jposton96a/emulation/tree/master/core

Wanted to give back to the resource that helped me so much with understanding emulation. Thanks for the fix

**Comment by jonesdy** [comment]
Awesome, I'm glad it helped.
